FROM openjdk:11

ARG PROFILE
ARG ADDITIONAL_OPTS

ENV PROFILE=${PROFILE}
ENV ADDITIONAL_OPTS=${PROFILE}


WORKDIR /opt/spring_boot

COPY /target/spring-boot.jar fullproject.jar

SHELL ["/bin/sh", "-c"]

EXPOSE 5005

EXPOSE 8080

CMD java ${ADDITIONAL_OPTS} -jar fullproject.jar --spring.profiles.active=${PROFILE}